
services:
  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    networks:
      - network

  backend:
    restart: on-failure
    build: ./backend
    networks:
      - network
  web:
    restart: on-failure
    build: 
      context: web
    networks:
      - network
  nginx:
    restart: on-failure
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web
    networks:
      - network


networks:
  network : 

  